# Generated by Django 2.1.4 on 2019-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to='Images')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
